# LAB3 : WRITE A PYTHON PROGRAM TO PERFORM ADVANCE OPERATIONS AND INDEX SLICING ON NUMPY ARRAY

## IMPORT NUMPY LIBRARY

In [1]:
import numpy as np

## Matrix multiplication 

In [3]:
A = np.array([[1,2],[2,3]])

B = np.array([[1,0],[0,1]])

print(A)
print(B)

[[1 2]
 [2 3]]
[[1 0]
 [0 1]]


In [4]:
# element wise matrix multiplication
print("Element wise matrix multiplication for A & B",A*B)

# matrix multiplication
# first way using @ operator
print("Matrix multiplication of A&B",A@B)

# second way dot()
print("Matrix multiplication", A.dot(B))

Element wise matrix multiplication for A & B [[1 0]
 [0 3]]
Matrix multiplication of A&B [[1 2]
 [2 3]]
Matrix multiplication [[1 2]
 [2 3]]


## Random function and other function

In [6]:
# create a generator for random values
#rg =  np.random.default_rng(1)
#print(rg)

b = np.random.rand(2,3)
print(b)

b = np.random.randn(2,3)
print(b)


b = np.random.randint(100, size = 10)
print(b)


[[0.96901361 0.99660432 0.92549491]
 [0.64303755 0.02175187 0.02699143]]
[[-0.3413726   0.01555022 -1.52108573]
 [-0.70624241  1.33433593  0.42095597]]
[42 72 29 56 72 42 50 69 66 53]


In [7]:
b = np.random.randint(10, size = (6,10))
print(b)

[[0 9 6 6 8 8 3 0 5 6]
 [0 5 5 7 6 8 4 0 4 4]
 [2 9 5 5 7 9 9 2 0 4]
 [8 1 8 5 4 4 0 9 3 2]
 [3 1 5 0 9 4 2 9 9 0]
 [4 6 5 5 8 9 3 2 6 4]]


## Mathematical Function of Numpy

In [5]:
b.sum()

217

In [6]:
b.max()

9

In [7]:
b.min()

0

In [8]:
b.mean()

3.6166666666666667

In [9]:
np.sin(b)

array([[-0.95892427,  0.98935825,  0.        ,  0.90929743,  0.        ,
         0.14112001, -0.2794155 ,  0.14112001,  0.84147098,  0.6569866 ],
       [ 0.14112001,  0.84147098,  0.41211849, -0.95892427, -0.2794155 ,
         0.        ,  0.90929743, -0.7568025 ,  0.90929743,  0.        ],
       [ 0.        , -0.7568025 ,  0.41211849,  0.98935825,  0.84147098,
        -0.2794155 ,  0.41211849,  0.        ,  0.84147098,  0.84147098],
       [ 0.84147098, -0.95892427,  0.84147098,  0.84147098,  0.90929743,
         0.98935825, -0.7568025 ,  0.98935825,  0.98935825,  0.98935825],
       [ 0.98935825,  0.14112001,  0.        ,  0.90929743, -0.95892427,
         0.90929743, -0.7568025 , -0.7568025 ,  0.14112001,  0.14112001],
       [ 0.14112001,  0.98935825,  0.        , -0.95892427, -0.95892427,
         0.        ,  0.        , -0.95892427,  0.14112001,  0.90929743]])

In [10]:
np.log10(25)

1.3979400086720377

In [11]:
np.exp(12)

162754.79141900392

In [12]:
np.round(12.33693)

12.0

## understand the axis in numpy array

In [11]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**when axis = 0 means column
axis =  1 means rows**

In [13]:
# column sum
print(b.sum(axis = 0))

[12 15 18 21]


In [14]:
# row sum
print(b.sum(axis = 1))

[ 6 22 38]


In [15]:
# min of each row
print(b.min(axis = 1))

[0 4 8]


In [16]:
# cumulative sum along each row  
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Indexing, Slicing and Iterating

In [8]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
#print the elements from 2 to 4
a[2:5]

array([2, 3, 4])

In [11]:
# print the last element
a[-1]

15

In [13]:
# print the all number expect last two
a[:-2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
# from a start to position 6,
# exclusive, set every 2nd element to 1000
a[:7:2] = 1000
print(a)

[1000    1 1000    3 1000    5 1000    7    8    9   10   11   12   13
   14   15]


In [25]:
# find all the elemnts in array greater than 10
# a[condition]
a[a > 10]

array([1000, 1000, 1000, 1000,   11,   12,   13,   14,   15])

## Array ceration using Function

In [26]:
# array creation from function
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


## Shape Manipulation

In [26]:
a = np.floor(10 * np.random.rand(3, 4))
print(a)
print("Shape",a.shape)

[[9. 9. 9. 4.]
 [4. 5. 2. 0.]
 [7. 6. 2. 7.]]
Shape (3, 4)


In [27]:
# flattened
print("Flattened array a = ",a.ravel())

Flattened arra a =  [9. 9. 9. 4. 4. 5. 2. 0. 7. 6. 2. 7.]


In [28]:
#transpose
print("Transpose of array a = ",a.T)

Transpose of array a =  [[9. 4. 7.]
 [9. 5. 6.]
 [9. 2. 2.]
 [4. 0. 7.]]


## Stacking together different arrays

In [30]:
a = np.floor(10 * np.random.rand(2, 2))

b = np.floor(10 * np.random.rand(2, 2))
print(a)
print(b)

[[4. 1.]
 [7. 8.]]
[[7. 6.]
 [0. 8.]]


In [31]:
# vertical stacking
print("AFTER VERTICAL STACKING --",np.vstack((a,b)))

AFTER VERTICAL STACKING -- [[4. 1.]
 [7. 8.]
 [7. 6.]
 [0. 8.]]


In [32]:
# horizontal stacking
print("AFTER HORIZONTAL STACKING --",np.hstack((a,b)))

AFTER HORIZONTAL STACKING -- [[4. 1. 7. 6.]
 [7. 8. 0. 8.]]


## How to get unique items and counts

In [33]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 
              17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [34]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


# count the no. of time unique value repeated
unique_values, indices , count = np.unique(a,
                return_index = True,return_counts=True)
print(unique_values)
print(indices)
print(count)

## Adding, removing, and sorting elements

In [36]:
# sorting
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
# concatenation
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Test Your K