# LAB1 : WRITE A PYTHOM PROGREM TO DEMOSTRATE THE NUMPY ARRAY AND ITS OPERATIONS

## INSTALATION OF NUMPY

In [1]:
# ! pip install numpy

### Import numpy

In [2]:
import numpy as np

C:\Users\student\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\student\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\Users\student\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


### create numpy array using reshape()

In [4]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Lets check attribute of numpy array

In [10]:
# check dimension 
print("dimension = ", a.ndim)

# check the shape (no. of rows and cols)
print("Shape of array = ", a.shape)

# check the size (no. of element)
print("Size of array = ", a.size)

# check the datatype of array
print("Data type of array = ", a.dtype)

#check itemsize of array
print("Itemsize = ", a.itemsize)

#Buffer containing actual data
print("Data adress= ", a.data)

dimension =  2
Shape of array =  (3, 5)
Size of array =  15
Data type of array =  int32
Itemsize =  4
Data adress=  <memory at 0x000001A1ACF16048>


# array creation 2

In [11]:
# 1-d array
b = np.array([1,2,3,4,5])
print(b)
print("dimension", b.ndim)

[1 2 3 4 5]
dimension 1


In [13]:
# 2-d array
c = np.array([(1,2,3),(4,5,6)])
print(c)
print("Dimension = ",c.ndim)
print("Shape = ",c.shape)

[[1 2 3]
 [4 5 6]]
Dimension =  2
Shape =  (2, 3)


In [15]:
# Task 1
# 3-d array
d = np.array([[(1,2,3),(4,5,6)], [(5,5,5),(4,4,6)]])
print(d)
print("Dimension = ",d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[5 5 5]
  [4 4 6]]]
Dimension =  3


#### Explicit datatype assignment

In [21]:
e =  np.array([(1,2,3),(4,5.2,6)],dtype = 'complex')
e

array([[1. +0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5.2+0.j, 6. +0.j]])

#### creation of some unique/standard array

In [22]:
# array of all zeros
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# array with all ones
o = np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# empty array
a = np.empty((2,2))
a

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 4.32887141e-312]])

In [27]:
# eye array to create diagonal matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# full array
a = np.full((3,4),100)
print(a)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


### arange, Reshape and resize methods revisited

```np.arange(lowerbound,upper bound,step)```

In [34]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.arange(2,20).reshape(2,9)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
np.arange(2,20,2).reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [44]:
np.arange(1,100,6.66).reshape(3,5)

array([[ 1.  ,  7.66, 14.32, 20.98, 27.64],
       [34.3 , 40.96, 47.62, 54.28, 60.94],
       [67.6 , 74.26, 80.92, 87.58, 94.24]])

### linspace function

*linspace is slicing function which slice range in number of steps*
```linspace(lower,upper,no. of elements)```

In [45]:
a =np.linspace(1, 17, 15).reshape(3,5)
print("a = ",a)

a =  [[ 1.          2.14285714  3.28571429  4.42857143  5.57142857]
 [ 6.71428571  7.85714286  9.         10.14285714 11.28571429]
 [12.42857143 13.57142857 14.71428571 15.85714286 17.        ]]


In [47]:
b = np.linspace(0, 10*3.14, 10).reshape(5,2)
print("b =",b)

b = [[ 0.          3.48888889]
 [ 6.97777778 10.46666667]
 [13.95555556 17.44444444]
 [20.93333333 24.42222222]
 [27.91111111 31.4       ]]


### Arithmetic Operations on numpy Array

In [48]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("Substration of two array",a-b)

print("Square of each elemnt in array b", b**2)

print("element which are greater than 35 in a",a>35)

print("Sin values of element in a",np.sin(a))

Substration of two array [20 29 38 47]
Square of each elemnt in array b [0 1 4 9]
element which are greater than 35 in a [False False  True  True]
Sin values of element in a [ 0.91294525 -0.98803162  0.74511316 -0.26237485]
